/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Inuciian (https://sketchfab.com/Inuciian)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/monk-character-8cacbd85a5b84f59a8c9000d7a6dcca2
title: Monk Character
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.06, 0.72]}>
          <primitive object={nodes.Armature_Monk_rootJoint} />
          <group position={[0, -0.12, -0.72]} rotation={[0, 0, -Math.PI]}>
            <mesh geometry={nodes.monk_0.geometry} material={materials.monk_material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/scene.gltf')
