/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Text3D(props) {
  const { nodes, materials } = useGLTF('/model/text3d.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={36.75} near={0.01} fov={35} position={[0.01, 0.09, 0.46]} />
      <mesh geometry={nodes['3D_Text_2_-_P'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.02, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_O'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.03, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_O_1'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.06, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_O_2'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.09, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_R'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.04, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_T'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.05, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_F'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.05, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_L'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.07, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_2_-_I'].geometry} material={materials['Fusion Elixir']} position={[0.13, 0.08, 0]} rotation={[Math.PI / 2, -1.57, Math.PI]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_G'].geometry} material={materials['Terrace View']} position={[-0.08, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_O'].geometry} material={materials['Terrace View']} position={[-0.05, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_R'].geometry} material={materials['Terrace View']} position={[-0.01, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_B'].geometry} material={materials['Terrace View']} position={[0.02, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_A'].geometry} material={materials['Terrace View']} position={[0.05, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_1_-_N'].geometry} material={materials['Terrace View']} position={[0.07, 0.02, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_Y'].geometry} material={materials.Hugo} position={[-0.11, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_A'].geometry} material={materials.Hugo} position={[-0.09, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_A_1'].geometry} material={materials.Hugo} position={[0.05, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_R'].geometry} material={materials.Hugo} position={[-0.06, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_O'].geometry} material={materials.Hugo} position={[-0.03, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_S'].geometry} material={materials.Hugo} position={[0.01, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_L'].geometry} material={materials.Hugo} position={[0.03, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
      <mesh geometry={nodes['3D_Text_-_V'].geometry} material={materials.Hugo} position={[0.08, 0.06, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0} />
    </group>
  )
}

useGLTF.preload('/model/text3d.glb')
