/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function YG(props) {
  const { nodes, materials } = useGLTF('/models/YG.gltf')
  console.log(materials)
  return (
  
    <group {...props} dispose={null}>
      <pointLight intensity={2} decay={2} distance={10000} color="#2b00ff" position={[3, 0, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={1} />
      <mesh geometry={nodes.Cone_2.geometry} material={materials['Clear Glass']} position={[-0.05, 0.01, 0]} rotation={[-0.87, -1.1, 1.25]} scale={0} />
      <mesh geometry={nodes.Cone.geometry} material={materials['Clear Glass']} position={[0.01, 0.02, 0.03]} rotation={[-0.62, 0.54, 0]} scale={0} />
      <mesh geometry={nodes.Cone_3.geometry} material={materials['Clear Glass']} position={[2, 1, 2]} rotation={[0.51, 0.58, 2.34]} scale={0.025} />
      <mesh geometry={nodes.Cone_1.geometry} material={materials['Clear Glass']} position={[-1.4, -1, 0.05]} rotation={[1.9, -0.47, Math.PI]} scale={0.05} />
      <mesh geometry={nodes['3D_Text_1_-_G'].geometry} material={materials.Blue} position={[0.4, -0.5, 0.5]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05} />
      <mesh geometry={nodes['3D_Text_-_Y'].geometry} material={materials.Wax} position={[-1, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05} />
    </group>
  )
}

useGLTF.preload('/models/YG.gltf')
