/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';

export function YG(props) {
  const { nodes, materials } = useGLTF('/models/YG.gltf')
  console.log(materials);
  return (
  
    <group {...props} dispose={null}>
      <pointLight intensity={2} decay={2} distance={10000} color="#2b00ff" position={[3, 0, 0.03]} rotation={[-Math.PI / 2, 0, 0]} scale={1} />
      <mesh geometry={nodes.Cone_2.geometry} material={materials['Clear Glass']} position={[-1, 3, 1.5]} rotation={[-0.87, -1.1, 1.25]} scale={0.01} />
      <mesh geometry={nodes.Cone.geometry} material={materials['Clear Glass']} position={[2, 2, 3]} rotation={[-0.62, 0.54, 0]} scale={0.01} />
      <mesh geometry={nodes.Cone_3.geometry} material={materials['Clear Glass']} position={[2, -0.5, 1.9]} rotation={[0.51, 0.58, 2.34]} scale={0.025} />
      <mesh geometry={nodes.Cone_1.geometry} material={materials['Clear Glass']} position={[-1, -0.7, 1.7]} rotation={[1.9, -0.47, Math.PI]} scale={0.05} material-color = 'Transparent'/>
      <mesh geometry={nodes['3D_Text_1_-_G'].geometry} material={materials.Blue} position={[0.4, -0.5, 0.9]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05} material-color = 'Gold' />
      <mesh geometry={nodes['3D_Text_-_Y'].geometry} material={materials.Wax} position={[-1, 0, -0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05} material-color="Red" />
    </group>
  )
}

useGLTF.preload('/models/YG.gltf')
